aliases:
  fleeks: cd ~/.local/share/fleek
  latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
  update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
  j!: jbang
allow_broken: false
auto_gc: true
bling: high
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
  autocommit: false
  autopull: true
  autopush: false
  enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays:
  {}
packages:
  - ansible
  - chkrootkit
  - cargo
  - dbus
  - dconf
  - dig
  - flac
  - fontconfig
  - gcc_multi
  - get_iplayer
  - github-cli
  - go
  - hub
  - jdk17
  - jq
  - krb5
  - lame
  - lm_sensors
  - maven
  - mediainfo
  - mkvtoolnix-cli
  - mlocate
  - openldap
  - openssl
  - rtorrent
  - syncthing
  - texinfoInteractive
  - tmux
  - virtualenv
  - weechat
  - wireguard-tools
  - wl-clipboard
  - yt-dlp
paths:
  - $HOME/go/bin
  - $HOME/.krew/bin
  - $HOME/.jbang/bin
  - $PYENV_ROOT/bin
  - $HOME/.cargo/bin
  - $HOME/bin
  - $HOME/.local/bin
programs:
  - dircolors
shell: bash
systems:
  - arch: x86_64
    home: ""
    hostname: localhost.localdomain
    os: linux
    user:
      email: nix@grdryn.xyz
      name: Gerard Ryan
      ssh_private_key_file: ~/.ssh/id_rsa
      ssh_public_key_file: ~/.ssh/id_rsa.pub
      username: gryan
    username: gryan
track: nixos-unstable
unfree: true
users: []
